<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }
    
    div#errors {
    	border:2px solid red;
    	padding:10px;
    	color:red;
    }
    
    ul.errors {
    	color:red;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div>
<?php
	$errors = $this->errors;
	if (count($errors)>0) {
		echo '<div id="errors">There were errors while processing your upload:';
		
		foreach($errors as $error) {
			echo sprintf(
				'<ul><li>%s</li></ul>',
				$error
			);
		}
		echo '</div>';
	}
?>
Please specify your Email Address and upload a CSV File.
<?php
	$this->form->setAction($this->url());
	echo $this->form;
?>
</div>